### ISSUE TITLE
Research and Plan for Implementing JWT Authentication

### ISSUE THREAD

**Issue by ravinder-chadha** [iRootsOrg/CodeBase#21]
- Research JWT authentication best practices.
- Choose a JWT library suitable for your backend framework (e.g., jsonwebtoken for Node.js)

**Comment by Ziphozenkosimthombe** [comment]
hey Sir so you need someone to implement the Jwt auth from the backend?

**Comment by ravinder-chadha** [comment]
> hey Sir so you need someone to implement the Jwt auth from the backend?

Thank you for your interest and efforts, but this is a private project, kept public to use rulesets.
