### ISSUE TITLE
Set Up Authentication Routes

### ISSUE THREAD

**Issue by ravinder-chadha** [iRootsOrg/CodeBase#22]
- Create a route for user registration (/register).
- Create a route for user login (/login).
- Create a route for token verification (optional, e.g., /verify).

**Comment by Ziphozenkosimthombe** [comment]
the user register route must be on the same file or separate file?

**Comment by KS963000** [comment]
I have created middleware that verifies JWT tokens. Is this sufficient, or do I also need to implement a /verify route?

**Comment by ravinder-chadha** [comment]
/verify route is not required as of now, what you have done should be enough
