### ISSUE TITLE
Create the UI for code reviewer

### ISSUE THREAD

**Issue by ravinder-chadha** [iRootsOrg/CodeBase#31]

**Comment by JAYANTJOSHI001** [comment]
@ravinder-chadha @harimurugan1989 Kindly checkout ui for reviewer code. Also give fb to it.
![MacBook Air - 10](https://github.com/iRootsOrg/CodeBase/assets/142237799/cb0f6cfb-1e26-4a17-b7d8-55e6a60c1256)
![MacBook Air - 9](https://github.com/iRootsOrg/CodeBase/assets/142237799/6872e24e-958b-4179-b2f7-1396eb779bc6)

**Comment by JAYANTJOSHI001** [comment]
@ravinder-chadha  @harimurugan1989  i have made changes to design. Kindly review.
![MacBook Air - 10](https://github.com/iRootsOrg/CodeBase/assets/142237799/5325abea-38a3-40b8-8694-9465fbfdc336)
![MacBook Air - 9](https://github.com/iRootsOrg/CodeBase/assets/142237799/e64bc144-3179-4e69-b420-989ed426ce47)

**Comment by JAYANTJOSHI001** [comment]
@ravinder-chadha @harimurugan1989  I have made a functionality to toolbar when click to add function in toolbar. Kindly review.
![Group 37555](https://github.com/iRootsOrg/CodeBase/assets/142237799/49210cff-c38c-44e0-9b33-050b1bf7805b)
