### ISSUE TITLE
Create dark mode for the current designs

### ISSUE THREAD

**Issue by ravinder-chadha** [iRootsOrg/CodeBase#48]

**Comment by JAYANTJOSHI001** [comment]
@ravinder-chadha @harimurugan1989 Done with dark mode.Kindly review it.
https://www.figma.com/design/Yug1fGPkwVo6J1Q9YtbRcx/Compiler-Module-Sitemap?node-id=0-1&t=7y216y75RJ75ZhGp-1

**Comment by ravinder-chadha** [comment]
Please create add and delete buttons for test cases, dark mode looks good!

**Comment by JAYANTJOSHI001** [comment]
@ravinder-chadha @harimurugan1989 I have added a new add  and delete buttons for test cases.Kindly review it.
https://www.figma.com/design/Yug1fGPkwVo6J1Q9YtbRcx/Compiler-Module-Sitemap?node-id=0-1&t=7y216y75RJ75ZhGp-1

**Comment by ravinder-chadha** [comment]
These seem fine to me.
