### ISSUE TITLE
Create setting screen and commands dialog box

### ISSUE THREAD

**Issue by ravinder-chadha** [iRootsOrg/CodeBase#49]

**Comment by JAYANTJOSHI001** [comment]
@harimurugan1989 @ravinder-chadha I have completed the designs for the command panel, incorporating all the necessary features for ease of use and functionality. I kindly request that you take the time to thoroughly review the designs and provide your feedback at your earliest convenience.
https://www.figma.com/design/Yug1fGPkwVo6J1Q9YtbRcx/Compiler-Module-Sitemap?node-id=0-1&t=0486HIW6VJrw9h1e-1

**Comment by JAYANTJOSHI001** [comment]
All changes are done. Kindly review this.
https://www.figma.com/design/Yug1fGPkwVo6J1Q9YtbRcx/Compiler-Module-Sitemap?node-id=0-1&t=0486HIW6VJrw9h1e-1
