### ISSUE TITLE
Create In review screen for the author

### ISSUE THREAD

**Issue by ravinder-chadha** [iRootsOrg/CodeBase#56]
- this is kind of the same screen where the reviewer reviews the code, but this will have the functionality to allow the author to reply back like a thread, do code modifications and resubmit for review

**Comment by JAYANTJOSHI001** [comment]
@ravinder-chadha @harimurugan1989 i completed this issue. Kindly give fb on it.
https://www.figma.com/design/Yug1fGPkwVo6J1Q9YtbRcx/Compiler-Module-Sitemap?node-id=0-1&t=q3xYzVXRgX7ue9me-1
