### ISSUE TITLE
Create wireframes and UI designs compatible with the existing review module

### ISSUE THREAD

**Issue by ravinder-chadha** [iRootsOrg/CodeBase#7]
- Create figma designs in coordination with the present review module.

The present UI can be found below:

![Image](https://github.com/iRootsOrg/CodeBase/assets/78102600/a10b722b-36a9-428e-a017-0e5413d2b48c)

![Image](https://github.com/iRootsOrg/CodeBase/assets/78102600/15146d6d-1455-44b5-a6a3-8432602ed550)

![Image](https://github.com/iRootsOrg/CodeBase/assets/78102600/181ef3f5-7214-4c61-81af-2869c127c192)

![Image](https://github.com/iRootsOrg/CodeBase/assets/78102600/21cd470b-8e79-4e5f-bddf-53d868cfcb8a)

![Image](https://github.com/iRootsOrg/CodeBase/assets/78102600/5e181ec2-d82b-4f26-84c5-4bfc497d7058)

**Comment by JAYANTJOSHI001** [comment]
Created an UI for compiler. Kindly review this.

![Screenshot 2024-06-29 115817](https://github.com/iRootsOrg/CodeBase/assets/142237799/386bf353-80d8-43fd-b94c-17f18566e4bb)
![Screenshot 2024-06-29 115800](https://github.com/iRootsOrg/CodeBase/assets/142237799/1fa1851b-dfd2-4511-9fdb-2902f83eca72)
![Screenshot 2024-06-29 115741](https://github.com/iRootsOrg/CodeBase/assets/142237799/5434469f-1712-4bca-9023-1de87f659467)

**Comment by ravinder-chadha** [comment]
@harimurugan1989 How does this looks fine to you.

**Comment by harimurugan1989** [comment]
Only color scheme needs to be changed. Remaining things are fine

**Comment by JAYANTJOSHI001** [comment]
I am uploading wireframe and UI and changed color gradient for buttons

![Screenshot 2024-07-01 113015](https://github.com/iRootsOrg/CodeBase/assets/142237799/796cde8f-e939-40ff-8596-f53f4555e404)
![Screenshot 2024-07-01 113004](https://github.com/iRootsOrg/CodeBase/assets/142237799/dbc48a64-81c1-4242-8310-3e3316a1e44e)
![Screenshot 2024-07-01 112949](https://github.com/iRootsOrg/CodeBase/assets/142237799/cb796e52-a410-400d-9927-0bd5850cc64a)

**Comment by ravinder-chadha** [comment]
We don't need to lock any test cases and we need an Upload or Submit button along with the run button as well. So that the person can submit, his/her code for review.

**Comment by ravinder-chadha** [comment]
@harimurugan1989 can you please review the colors now?

**Comment by JAYANTJOSHI001** [comment]
> We don't need to lock any test cases and we need an Upload or Submit button along with the run button as well. So that the person can submit, his/her code for review.

@ravinder-chadha in toolbar there is one upload and one save button there which can be treated for uploading and submitting review

**Comment by ravinder-chadha** [comment]
Please add a submit button as discussed in the meeting and then we are good to close this issue.

**Comment by JAYANTJOSHI001** [comment]
@ravinder-chadha sir ,I have add submit button in design. Kindly review it.
![MacBook Air - 8](https://github.com/iRootsOrg/CodeBase/assets/142237799/f9c11487-ff1d-4018-9a53-9d58ddd6fd89)
![MacBook Air - 7](https://github.com/iRootsOrg/CodeBase/assets/142237799/0cd2e4df-92a8-4d39-9bdf-88efd9a3006c)
