### ISSUE TITLE
Research and Find the code compilation APIs

### ISSUE THREAD

**Issue by ravinder-chadha** [iRootsOrg/CodeBase#72]
- Find the APIs of code compilers that we can leverage
- Instead of installing our own compilers we can get it compiled from some API
- What is the cost of the various API. Make a table of language vs cost for different APIs.

**Comment by SumitTeerthani** [comment]
Glot Api  (Free Api)
 https://glot.io/
It can Compile languages like python, c,c++,java,javascript and many more . (it does not include Matlab compiler)



![Image](https://github.com/iRootsOrg/CodeBase/assets/96737999/bc15adb3-f581-4d1b-adeb-c4ac19e5aa44)
