### ISSUE TITLE
Create the UI of the payment for purchasing the code

### ISSUE THREAD

**Issue by ravinder-chadha** [iRootsOrg/CodeBase#73]
when the reviewer click on the buy button he must see some page with the amount that is quoted by author. The author can sell a part of code, as well as the whole project. Thus the pricing needs to be listed differently giving option to the reviewer to purchase.

**Comment by JAYANTJOSHI001** [comment]
@ravinder-chadha I have completed this issue. Kindly review and close it.
https://www.figma.com/design/Yug1fGPkwVo6J1Q9YtbRcx/Compiler-Module-Sitemap?node-id=0-1&t=r2yfQHmaz8wLfszm-1

**Comment by ravinder-chadha** [comment]
Please redesign with some better ideation, this doesn't look good

**Comment by ravinder-chadha** [comment]
The price font is too big, the buy button is too small
