### ISSUE TITLE
Add the mechanism to verify if the user exists

### ISSUE THREAD

**Issue by ravinder-chadha** [iRootsOrg/CodeBase#93]
- This is need for invite functionality on frontend
- If the user is not verified yet, then show that the user needs to register on the platform first i.e. raise an error
- Then the user can be added to the as co-author to the code

**Comment by 17himanshu** [comment]
@ravinder-chadha  Sir, I am just asking for clarification on this issue do we have to implement code for inviting co-author as well , I guess that's a separate API. What I am understanding is we have to check if user is registered or not and if not ask him to register . Please correct me if there's misunderstanding
